# Generated by Django 3.0.4 on 2020-05-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Categoria'),
        ),
    ]
