# Generated by Django 3.0.4 on 2020-05-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_auto_20200519_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='clave',
            field=models.CharField(default=1, max_length=30, verbose_name='Clave'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(default=1, upload_to='articulos', verbose_name='Imagen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(default=1, max_length=150, verbose_name='Artícuclo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Precio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='Unidades'),
            preserve_default=False,
        ),
    ]
