# Generated by Django 3.0.4 on 2020-05-20 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_auto_20200519_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(null=True, verbose_name='Articulos vendidos')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total Venta')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('detalle_venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articulos.DetalleVenta', verbose_name='DetalleVenta')),
            ],
        ),
    ]
